### ISSUE TITLE
totally failed at pipeline to save .pdfs in matlab that interact nicely as linked files in illustrator

### ISSUE THREAD

**Issue by jcbyts** [mobeets/gaborMotionPulses#99]
I have agonized over this for the last 8 hours. It seems matlab's plotting is totally borked and any final figures are going to require tons of manual editing. I'm voting for saving everything as .png for now and avoid vector graphics until we have a final manuscript.

**Comment by jcbyts** [comment]
I've tried pretty much every single third party matlab figure exporting code
hgexport
export_fig
plot2svg
matlab2frag

plot2svg is the coolest because it actually produces nice vector graphics for illustrator, but it doesn't have support for quivers or annotations.

**Comment by mobeets** [comment]
@jcbyts can I close this given your discovery of [Figure Composer](https://sites.google.com/a/srscicomp.com/datanav/download-files) ?
